language: node_js
services: mongodb
node_js:
  - "11.11.0"
install:
 npm install
env:
  global:
    - CC_TEST_REPORTER_ID=d7fc75877b9f45cc71f60e3e60f7a6720e7bca91f6b34744b8f2f26c40e54ecb
    - MONGODB_VERSION=4.0.3
    - TEST_DATABASE_URL= "mongodb://localhost:27017/Banka-lite"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sleep 15
script:
  - npm ci
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls
  - npm run report-coverage
  - npm run codeclimate-report
  - ./node_modules/.bin/mocha ./app/test/**/*.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
