version: 2
jobs:
  build:
    working_directory: ~/Banka-lite
    docker:
      - image: circleci/node:11.11.0
      - image: mongo:4.0.3
    environment:
      - NODE_ENV: test
      - TEST_DATABASE_URL: "mongodb://localhost:27017/Banka-lite"
    dependencies:
        cache_directories:
          - mongodb-linux-x86_64-ubuntu1204-3.2.0
        pre:
          - if [[ ! -d mongodb-linux-x86_64-ubuntu1204-3.2.0 ]]; then wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1204-3.2.0.tgz && tar xvzf mongodb-linux-x86_64-ubuntu1204-3.2.0.tgz; fi
          - sudo stop mongodb
          - sudo cp mongodb-linux-x86_64-ubuntu1204-3.2.0/bin/* /usr/bin
          - sudo start mongodb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: npm run test
